name: Publish pkg.pr.new

on:
  pull_request:
    paths:
      - 'src/**'

permissions:
  contents: read
  id-token: write

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  pkg-pr-new:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v7

      - name: Use pnpm
        uses: pnpm/action-setup@v6

      - uses: actions/setup-node@v7
        with:
          node-version: lts/*
          cache: pnpm

      - name: 📦 Install dependencies
        run: pnpm i

      - name: 🛠 Build project
        run: pnpm build

      - name: Publish pkg.pr.new
        run: npx pkg-pr-new publish
